name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore DebugProbe.AspNetCore.sln

      - name: Build
        run: dotnet build DebugProbe.AspNetCore.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test DebugProbe.AspNetCore.sln --no-build --configuration Release
